import type { Field, GroupKey, SectionContent, SectionDef } from "@/lib/cms/types";

/**
 * Danh sách MỌI khối nội dung chỉnh sửa được từ /admin/noi-dung.
 * Thêm khối mới = thêm 1 định nghĩa ở đây + gọi getSection("khóa") trong component.
 * Trang admin tự sinh form từ `fields`. `defaults` là nội dung gốc đang chạy trên
 * website, nên khi chưa lưu gì thì website trông y như cũ.
 */

export const CMS_GROUPS: { key: GroupKey; label: string; description: string }[] = [
  {
    key: "global",
    label: "Thông tin chung",
    description: "Thanh thông báo trên cùng và chân trang (footer) — hiện ở mọi trang.",
  },
  {
    key: "home",
    label: "Trang chủ",
    description: "Các khối nội dung của trang chủ dopamind.vn.",
  },
  {
    key: "story",
    label: "Câu chuyện DOPAMIND",
    description: "Banner, câu chuyện thương hiệu, trụ cột và lời kêu gọi ở /cau-chuyen-dopamind.",
  },
  {
    key: "shop",
    label: "Trang sản phẩm",
    description: "Banner và phần giới thiệu danh mục tại /san-pham.",
  },
  {
    key: "journal",
    label: "Nhật ký & Bài viết",
    description: "Trang /nhat-ky và trang /bai-viet.",
  },
];

const heroFields: Field[] = [
  { key: "eyebrow", type: "text", label: "Dòng nhỏ phía trên", max: 80 },
  { key: "line1", type: "text", label: "Tiêu đề — dòng 1", max: 40, required: true },
  { key: "line2", type: "text", label: "Tiêu đề — dòng 2 (chữ nghiêng màu tím)", max: 40 },
  { key: "body", type: "textarea", label: "Mô tả ngắn", max: 300 },
  { key: "primaryLabel", type: "text", label: "Nút chính — chữ", max: 40 },
  { key: "primaryHref", type: "url", label: "Nút chính — đường dẫn", help: "Ví dụ: /san-pham" },
  { key: "secondaryLabel", type: "text", label: "Liên kết phụ — chữ", max: 50 },
  { key: "secondaryHref", type: "url", label: "Liên kết phụ — đường dẫn", help: "Ví dụ: /cau-chuyen-dopamind" },
];

export const SECTION_DEFS: SectionDef[] = [
  // ---------------------------------------------------------------- Thông tin chung
  {
    key: "global.announcement",
    group: "global",
    label: "Thanh thông báo",
    description: "Dòng chữ trên cùng của website. Để trống ô nội dung để ẩn thanh này.",
    path: "/",
    fields: [
      { key: "text", type: "text", label: "Nội dung thông báo", max: 140, help: "Để trống để ẩn thanh thông báo." },
      { key: "href", type: "url", label: "Đường dẫn khi bấm (không bắt buộc)", help: "Để trống nếu không cần bấm được." },
    ],
    defaults: {
      text: "Nghi thức 15 phút mỗi ngày — từ quá tải đến cân bằng",
      href: "",
    },
  },
  {
    key: "global.footer",
    group: "global",
    label: "Chân trang (footer)",
    description: "Câu giới thiệu, dòng bản quyền và các liên kết mạng xã hội ở cuối trang.",
    path: "/",
    fields: [
      { key: "tagline", type: "textarea", label: "Câu giới thiệu dưới logo", max: 200 },
      {
        key: "copyright",
        type: "text",
        label: "Dòng bản quyền",
        max: 120,
        help: "Năm hiện tại được tự thêm phía trước (© 2026 ...).",
      },
      {
        key: "social",
        type: "list",
        label: "Liên kết mạng xã hội",
        itemLabel: "Liên kết",
        itemTitleKey: "label",
        max: 8,
        fields: [
          { key: "label", type: "text", label: "Tên (Instagram, TikTok...)", max: 30, required: true },
          { key: "href", type: "url", label: "Đường dẫn", help: "Dán link trang của bạn, ví dụ https://instagram.com/...", required: true },
        ],
      },
    ],
    defaults: {
      tagline: "Mind–Skin Care. Nghi thức 15 phút mỗi ngày, từ quá tải đến cân bằng.",
      copyright: "Dopamind Mask Story. Tất cả các quyền được bảo lưu.",
      social: [
        { label: "Instagram", href: "#" },
        { label: "TikTok", href: "#" },
        { label: "Spotify", href: "#" },
      ],
    },
  },

  // ---------------------------------------------------------------- Trang chủ
  {
    key: "home.hero",
    group: "home",
    label: "Banner đầu trang chủ (Hero)",
    description: "Tiêu đề lớn, mô tả và hai nút ở đầu trang chủ. Ảnh nền của banner chưa chỉnh được ở đây.",
    path: "/",
    fields: heroFields,
    defaults: {
      eyebrow: "DOPAMIND MASK STORY / MIND–SKIN CARE",
      line1: "Mask",
      line2: "Skin Mind",
      body: "Dành 15 phút để làn da được chăm sóc và bạn có một khoảng thời gian thật sự dành cho chính mình.",
      primaryLabel: "KHÁM PHÁ SẢN PHẨM",
      primaryHref: "/san-pham",
      secondaryLabel: "CÂU CHUYỆN CỦA CHÚNG TÔI",
      secondaryHref: "/cau-chuyen-dopamind",
    },
  },
  {
    key: "home.productFamilies",
    group: "home",
    label: "Trang chủ — dòng sản phẩm",
    description: "Phần giới thiệu và 6 ô dòng sản phẩm ngay dưới banner đầu trang.",
    path: "/",
    fields: [
      { key: "eyebrow", type: "text", label: "Dòng nhỏ phía trên", max: 60 },
      { key: "title", type: "textarea", label: "Tiêu đề", max: 120, required: true, help: "Xuống dòng trong ô để xuống dòng trên website." },
      { key: "body", type: "textarea", label: "Mô tả", max: 400 },
      { key: "ctaLabel", type: "text", label: "Chữ liên kết", max: 60 },
      { key: "ctaHref", type: "url", label: "Đường dẫn liên kết" },
      {
        key: "categories",
        type: "list",
        label: "Các dòng sản phẩm",
        itemLabel: "Dòng sản phẩm",
        itemTitleKey: "label",
        min: 1,
        max: 8,
        fields: [
          { key: "label", type: "text", label: "Tên", max: 80, required: true },
          { key: "href", type: "url", label: "Đường dẫn", required: true },
          { key: "image", type: "image", label: "Ảnh", required: true, help: "Tỉ lệ khuyến nghị 4:3." },
          { key: "alt", type: "text", label: "Mô tả ảnh", max: 160 },
        ],
      },
    ],
    defaults: {
      eyebrow: "DÒNG SẢN PHẨM",
      title: "18 sản phẩm.\n6 dòng chăm sóc.",
      body: "Từ mặt nạ chuyên sâu đến các bước chăm sóc hằng ngày, khám phá DOPAMIND theo dòng sản phẩm phù hợp với khoảng thời gian của bạn.",
      ctaLabel: "KHÁM PHÁ TẤT CẢ SẢN PHẨM →",
      ctaHref: "/san-pham",
      categories: [
        { label: "MTS Dual Layer Sheet", href: "/san-pham?danh-muc=mts-dual-layer-sheet", image: "/images/homepage/products/P01.png", alt: "Mặt nạ MTS Dual Layer Sheet DOPAMIND" },
        { label: "Bộ HA", href: "/san-pham?danh-muc=bo-ha", image: "/images/homepage/science/SS01.png", alt: "Dòng sản phẩm Bộ HA DOPAMIND" },
        { label: "Mặt nạ phôi dừa", href: "/san-pham?danh-muc=mat-na-phoi-dua", image: "/images/homepage/campaign/CB01.png", alt: "Mặt nạ phôi dừa DOPAMIND" },
        { label: "Mặt nạ thạch", href: "/san-pham?danh-muc=mat-na-thach", image: "/images/homepage/ritual/R03.png", alt: "Mặt nạ thạch DOPAMIND" },
        { label: "Mặt nạ giảm mụn phục hồi", href: "/san-pham?danh-muc=mat-na-giam-mun-phuc-hoi", image: "/images/homepage/featured/FR01.png", alt: "Mặt nạ giảm mụn phục hồi DOPAMIND" },
        { label: "Mặt nạ đất sét", href: "/san-pham?danh-muc=mat-na-dat-set", image: "/images/homepage/moments/M04.png", alt: "Mặt nạ đất sét DOPAMIND" },
      ],
    },
  },
  {
    key: "home.brandStrip",
    group: "home",
    label: "Trang chủ — dải thông tin thương hiệu",
    description: "Bốn thông điệp ngắn nằm giữa phần dòng sản phẩm và câu chuyện khoa học.",
    path: "/",
    fields: [
      {
        key: "items",
        type: "list",
        label: "Thông điệp",
        itemLabel: "Thông điệp",
        itemTitleKey: "label",
        min: 1,
        max: 6,
        fields: [
          { key: "number", type: "text", label: "Số thứ tự", max: 4 },
          { key: "label", type: "text", label: "Tiêu đề", max: 80, required: true },
          { key: "description", type: "text", label: "Mô tả", max: 140 },
        ],
      },
    ],
    defaults: {
      items: [
        { number: "01", label: "MIND–SKIN CARE", description: "Chăm sóc làn da và khoảng thời gian của bạn." },
        { number: "02", label: "15 PHÚT", description: "Một nghi thức nhỏ trong ngày." },
        { number: "03", label: "18 sản phẩm & 6 dòng chăm sóc", description: "Khám phá theo nhu cầu của bạn." },
        { number: "04", label: "DOPAMIND MASK STORY", description: "Từ quá tải đến cân bằng." },
      ],
    },
  },
  {
    key: "home.scienceEmotion",
    group: "home",
    label: "Trang chủ — DOPA × MIND",
    description: "Khối giới thiệu triết lý kết nối khoa học làn da và cảm xúc.",
    path: "/",
    fields: [
      { key: "title", type: "textarea", label: "Tiêu đề", max: 120, required: true, help: "Xuống dòng trong ô để xuống dòng trên website." },
      { key: "body", type: "textarea", label: "Mô tả", max: 500 },
      { key: "ctaLabel", type: "text", label: "Chữ liên kết", max: 70 },
      { key: "ctaHref", type: "url", label: "Đường dẫn liên kết" },
      {
        key: "panels",
        type: "list",
        label: "Hai ô DOPA / MIND",
        itemLabel: "Ô nội dung",
        itemTitleKey: "title",
        min: 1,
        max: 2,
        fields: [
          { key: "title", type: "text", label: "Tiêu đề", max: 30, required: true },
          { key: "concepts", type: "textarea", label: "Các ý nhỏ", max: 240, help: "Ngăn cách các ý bằng dấu |." },
        ],
      },
    ],
    defaults: {
      title: "Khoa học\nchạm vào cảm xúc.",
      body: "Khi làn da khỏe mạnh, tâm trí cũng nhẹ nhàng hơn. Dopamind tin rằng chăm sóc da không chỉ là làm đẹp mà còn là nuôi dưỡng cảm xúc tích cực từ bên trong.",
      ctaLabel: "TÌM HIỂU TRIẾT LÝ THƯƠNG HIỆU →",
      ctaHref: "/cau-chuyen-dopamind",
      panels: [
        { title: "DOPA", concepts: "SKIN SCIENCE | FOR A BRIGHTER YOU | Hiệu quả từ khoa học. Thành phần tinh khiết. Làn da khỏe mạnh mỗi ngày" },
        { title: "MIND", concepts: "A CALMER MIND | A BRIGHTER LIFE" },
      ],
    },
  },
  {
    key: "home.skinScience",
    group: "home",
    label: "Trang chủ — khoa học làn da",
    description: "Banner hình ảnh và thông điệp về công nghệ, công dụng của sản phẩm.",
    path: "/",
    fields: [
      { key: "eyebrow", type: "text", label: "Dòng nhỏ phía trên", max: 60 },
      { key: "title", type: "textarea", label: "Tiêu đề", max: 120, required: true },
      { key: "benefitsLabel", type: "text", label: "Nhãn công dụng", max: 60 },
      { key: "benefits", type: "textarea", label: "Các công dụng", max: 300 },
      { key: "ctaLabel", type: "text", label: "Chữ trên nút", max: 60 },
      { key: "ctaHref", type: "url", label: "Đường dẫn nút" },
      { key: "image", type: "image", label: "Ảnh", required: true, help: "Tỉ lệ khuyến nghị 4:3." },
      { key: "imageAlt", type: "text", label: "Mô tả ảnh", max: 180 },
    ],
    defaults: {
      eyebrow: "KHOA HỌC LÀN DA",
      title: "Tinh hoa khoa học\ntrong từng lớp mặt nạ",
      benefitsLabel: "CÔNG DỤNG CHÍNH",
      benefits: "Cấp ẩm · Làm dịu · Phục hồi · Sáng da · Chống lão hóa · Chăm sóc lỗ chân lông",
      ctaLabel: "KHÁM PHÁ CÔNG NGHỆ",
      ctaHref: "/cau-chuyen-dopamind",
      image: "/images/homepage/science/SS01.png",
      imageAlt: "Cận cảnh chất liệu mặt nạ và tinh chất Dopamind Mask Story",
    },
  },
  {
    key: "home.ritual",
    group: "home",
    label: "Trang chủ — nghi thức 15 phút",
    description: "Nội dung của bộ đếm 15 phút và các lời nhắc trong nghi thức.",
    path: "/#nghi-thuc-15-phut",
    fields: [
      { key: "eyebrow", type: "text", label: "Dòng nhỏ phía trên", max: 60 },
      { key: "title", type: "textarea", label: "Tiêu đề", max: 140, required: true },
      { key: "body", type: "textarea", label: "Mô tả", max: 300 },
      { key: "statement", type: "textarea", label: "Thông điệp bên phải", max: 200 },
      { key: "completedEyebrow", type: "text", label: "Khi hoàn tất — dòng nhỏ", max: 60 },
      { key: "completedBody", type: "textarea", label: "Khi hoàn tất — lời nhắn", max: 240 },
      { key: "startLabel", type: "text", label: "Nút bắt đầu", max: 40 },
      { key: "pauseLabel", type: "text", label: "Nút tạm dừng", max: 40 },
      { key: "resumeLabel", type: "text", label: "Nút tiếp tục", max: 40 },
      { key: "resetLabel", type: "text", label: "Nút đặt lại", max: 40 },
      {
        key: "revealLines",
        type: "list",
        label: "Lời nhắc lần lượt",
        itemLabel: "Lời nhắc",
        itemTitleKey: "text",
        min: 1,
        max: 3,
        fields: [{ key: "text", type: "text", label: "Nội dung", max: 100, required: true }],
      },
    ],
    defaults: {
      eyebrow: "DOPAMIND RITUAL",
      title: "15 phút mỗi ngày. Từ quá tải đến cân bằng.",
      body: "Chỉ 15 phút, để tạm rời khỏi nhịp độ bên ngoài và trở lại với chính mình.",
      statement: "Những khoảnh khắc nhỏ tạo nên thay đổi lớn.",
      completedEyebrow: "RESET HOÀN TẤT",
      completedBody: "Chào mừng bạn trở lại. Những khoảnh khắc nhỏ tạo nên thay đổi lớn.",
      startLabel: "BẮT ĐẦU RESET",
      pauseLabel: "TẠM DỪNG",
      resumeLabel: "TIẾP TỤC",
      resetLabel: "ĐẶT LẠI",
      revealLines: [
        { text: "ĐẶT ĐIỆN THOẠI XUỐNG." },
        { text: "ĐẮP MẶT NẠ." },
        { text: "TẮT THẾ GIỚI BÊN NGOÀI." },
      ],
    },
  },
  {
    key: "home.journal",
    group: "home",
    label: "Trang chủ — câu chuyện cảm hứng",
    description: "Tiêu đề và các thẻ bài viết ở gần cuối trang chủ.",
    path: "/",
    fields: [
      { key: "title", type: "text", label: "Tiêu đề", max: 100, required: true },
      { key: "ctaLabel", type: "text", label: "Chữ liên kết xem tất cả", max: 50 },
      { key: "ctaHref", type: "url", label: "Đường dẫn xem tất cả" },
      {
        key: "cards",
        type: "list",
        label: "Các câu chuyện",
        itemLabel: "Câu chuyện",
        itemTitleKey: "title",
        min: 1,
        max: 6,
        fields: [
          { key: "category", type: "text", label: "Chủ đề", max: 50 },
          { key: "title", type: "text", label: "Tiêu đề", max: 140, required: true },
          { key: "intro", type: "textarea", label: "Mô tả", max: 360 },
          { key: "href", type: "url", label: "Đường dẫn", required: true },
          { key: "image", type: "image", label: "Ảnh", required: true, help: "Tỉ lệ khuyến nghị 4:5." },
          { key: "alt", type: "text", label: "Mô tả ảnh", max: 180 },
        ],
      },
    ],
    defaults: {
      title: "Những câu chuyện cảm hứng",
      ctaLabel: "XEM TẤT CẢ →",
      ctaHref: "/nhat-ky",
      cards: [
        { category: "LÀN DA & CẢM XÚC", title: "Khi làn da khỏe hơn, bạn rạng rỡ hơn", intro: "Một vài phút chăm sóc da, một chút bình yên cho tâm trí — cùng nhìn lại mối liên hệ giữa làn da và cảm xúc.", href: "/nhat-ky", image: "/images/homepage/collections/C03.png", alt: "Làn da rạng rỡ sau nghi thức chăm sóc Dopamind Mask Story" },
        { category: "HƯỚNG DẪN", title: "5 bước cho trải nghiệm đắp mặt nạ trọn vẹn hơn", intro: "Từ làm sạch đến thư giãn — cách biến 15 phút đắp mặt nạ thành một nghi thức trọn vẹn.", href: "/nhat-ky", image: "/images/homepage/ritual/R01.png", alt: "Hướng dẫn đắp mặt nạ Dopamind Mask Story từng bước" },
        { category: "LIFESTYLE", title: "Sống chậm, đẹp hơn mỗi ngày", intro: "Những thói quen nhỏ, lặp lại mỗi ngày, dần trở thành phong cách sống chậm rãi và dịu dàng hơn.", href: "/nhat-ky", image: "/images/homepage/moments/M01.png", alt: "Buổi sáng sống chậm cùng Dopamind Mask Story" },
      ],
    },
  },
  {
    key: "home.newsletter",
    group: "home",
    label: "Trang chủ — đăng ký nhận tin",
    description: "Nội dung khối đăng ký email ở cuối trang chủ.",
    path: "/",
    fields: [
      { key: "title", type: "text", label: "Tiêu đề", max: 100, required: true },
      { key: "body", type: "textarea", label: "Mô tả", max: 260 },
      { key: "placeholder", type: "text", label: "Gợi ý trong ô email", max: 60 },
      { key: "buttonLabel", type: "text", label: "Chữ trên nút", max: 30 },
      { key: "thankYou", type: "textarea", label: "Lời cảm ơn sau khi gửi", max: 180 },
    ],
    defaults: {
      title: "Nhận một lời nhắc dịu dàng.",
      body: "Cập nhật những câu chuyện, nghi thức và điều mới từ DOPAMIND.",
      placeholder: "Email của bạn",
      buttonLabel: "ĐĂNG KÝ",
      thankYou: "Cảm ơn bạn đã tham gia cùng Dopamind Mask Story.",
    },
  },

  // ---------------------------------------------------------------- Câu chuyện thương hiệu
  {
    key: "story.hero",
    group: "story",
    label: "Câu chuyện — banner đầu trang",
    description: "Ảnh, tiêu đề, mô tả và ba nhãn thương hiệu ở đầu trang Câu chuyện DOPAMIND.",
    path: "/cau-chuyen-dopamind",
    fields: [
      { key: "enabled", type: "boolean", label: "Hiển thị khối" },
      { key: "eyebrow", type: "text", label: "Dòng nhỏ", max: 80 },
      { key: "title1", type: "text", label: "Tiêu đề — dòng 1", max: 60, required: true },
      { key: "title2", type: "text", label: "Tiêu đề — dòng 2", max: 60 },
      { key: "title3", type: "text", label: "Tiêu đề — dòng 3 (nghiêng)", max: 60 },
      { key: "title4", type: "text", label: "Tiêu đề — dòng 4 (nghiêng)", max: 60 },
      { key: "body", type: "textarea", label: "Mô tả", max: 600 },
      { key: "note", type: "text", label: "Thông điệp ngắn", max: 180 },
      { key: "image", type: "image", label: "Ảnh banner", required: true, help: "Tỉ lệ khuyến nghị 4:5; nên chừa khoảng trống quanh chủ thể." },
      { key: "imageAlt", type: "text", label: "Mô tả ảnh", max: 220 },
      {
        key: "labels",
        type: "list",
        label: "Nhãn dưới banner",
        itemLabel: "Nhãn",
        itemTitleKey: "text",
        min: 1,
        max: 3,
        fields: [{ key: "text", type: "text", label: "Nội dung", max: 60, required: true }],
      },
    ],
    defaults: {
      enabled: true,
      eyebrow: "DOPAMIND / MIND–SKIN CARE",
      title1: "DOPAMIND",
      title2: "Hơn cả",
      title3: "một chiếc",
      title4: "mặt nạ.",
      body: "DOPAMIND được tạo nên từ DOPA + MIND — nơi chăm sóc da không chỉ là một bước trong routine, mà còn là một khoảng thời gian để bạn chậm lại và trở về với chính mình.",
      note: "Một chiếc mặt nạ là sản phẩm. 15 phút mới là trải nghiệm.",
      image: "/images/homepage/hero/H02.png",
      imageAlt: "Một người phụ nữ thư giãn trong nghi thức chăm sóc da DOPAMIND",
      labels: [{ text: "SKIN SCIENCE" }, { text: "MIND RESET" }, { text: "MASK EXPERIENCE" }],
    },
  },
  {
    key: "story.meaning",
    group: "story",
    label: "Câu chuyện — ý nghĩa tên thương hiệu",
    description: "Phần giải thích DOPA, MIND và MASK STORY.",
    path: "/cau-chuyen-dopamind",
    fields: [
      { key: "enabled", type: "boolean", label: "Hiển thị khối" },
      { key: "eyebrow", type: "text", label: "Dòng nhỏ", max: 80 },
      { key: "title", type: "textarea", label: "Tiêu đề", max: 180, help: "Xuống dòng trong ô để xuống dòng trên website." },
      { key: "body1", type: "textarea", label: "Đoạn mô tả 1", max: 500 },
      { key: "body2", type: "textarea", label: "Đoạn mô tả 2", max: 500 },
      {
        key: "panels",
        type: "list",
        label: "Ba ô ý nghĩa",
        itemLabel: "Ô nội dung",
        itemTitleKey: "title",
        min: 3,
        max: 3,
        fields: [
          { key: "title", type: "text", label: "Tên", max: 40, required: true },
          { key: "statement", type: "text", label: "Thông điệp", max: 120 },
          { key: "body", type: "textarea", label: "Mô tả", max: 360 },
        ],
      },
    ],
    defaults: {
      enabled: true,
      eyebrow: "Ý NGHĨA TÊN THƯƠNG HIỆU",
      title: "DOPAMIND\nđược tạo nên\ntừ những giá trị\nđẹp và thật.",
      body1: "DOPAMIND bắt đầu từ một ý niệm đơn giản: việc chăm sóc da có thể trở thành một khoảng dừng dễ chịu trong ngày.",
      body2: "DOPA, MIND và MASK STORY kết nối cảm xúc, thói quen và trải nghiệm chăm sóc da thành một câu chuyện thống nhất.",
      panels: [
        { title: "DOPA", statement: "NIỀM VUI TỪ NHỮNG ĐIỀU NHỎ.", body: "Những khoảnh khắc tích cực đôi khi bắt đầu từ một điều rất nhỏ — vài phút dành riêng cho chính mình." },
        { title: "MIND", statement: "MỘT TÂM TRÍ AN YÊN HƠN.", body: "Khi bạn dành thời gian cho bản thân, skincare có thể trở thành một nghi thức giúp nhịp sống chậm lại." },
        { title: "MASK STORY", statement: "", body: "Mỗi sản phẩm là một chương trong hành trình chăm sóc bản thân." },
      ],
    },
  },
  {
    key: "story.pillars",
    group: "story",
    label: "Câu chuyện — ba trụ cột",
    description: "Nội dung ba trụ cột Khoa học, Cảm xúc và Trải nghiệm.",
    path: "/cau-chuyen-dopamind",
    fields: [
      { key: "enabled", type: "boolean", label: "Hiển thị khối" },
      { key: "eyebrow", type: "text", label: "Dòng nhỏ", max: 100 },
      { key: "title", type: "textarea", label: "Tiêu đề", max: 180 },
      { key: "body", type: "textarea", label: "Mô tả", max: 500 },
      {
        key: "pillars",
        type: "list",
        label: "Các trụ cột",
        itemLabel: "Trụ cột",
        itemTitleKey: "title",
        min: 3,
        max: 3,
        fields: [
          { key: "title", type: "text", label: "Tên tiếng Anh", max: 60, required: true },
          { key: "label", type: "text", label: "Tên tiếng Việt", max: 80 },
          { key: "body", type: "textarea", label: "Mô tả", max: 400 },
        ],
      },
    ],
    defaults: {
      enabled: true,
      eyebrow: "BA TRỤ CỘT TẠO NÊN DOPAMIND",
      title: "Khoa học,\ncảm xúc\nvà trải nghiệm.",
      body: "DOPAMIND tiếp cận việc chăm sóc da từ ba góc nhìn: nghiêm túc với làn da, tinh tế với cảm xúc và có chủ đích trong từng trải nghiệm.",
      pillars: [
        { title: "SKIN SCIENCE", label: "KHOA HỌC LÀN DA", body: "Mọi thông tin về công thức, thành phần và công dụng chỉ được công bố khi có dữ liệu chính thức." },
        { title: "MIND RESET", label: "15 PHÚT DÀNH CHO BẠN", body: "Một khoảng dừng nhỏ để bạn tạm rời khỏi nhịp độ bên ngoài và trở lại với chính mình." },
        { title: "MASK EXPERIENCE", label: "TRẢI NGHIỆM MẶT NẠ", body: "Chất liệu, cấu trúc và trải nghiệm sản phẩm được kể bằng thông tin thực khi dữ liệu chính thức sẵn sàng." },
      ],
    },
  },
  {
    key: "story.origin",
    group: "story",
    label: "Câu chuyện — khởi nguồn Việt Nam",
    description: "Thông điệp nguồn gốc thương hiệu và ba ý niệm bên dưới bản đồ.",
    path: "/cau-chuyen-dopamind",
    fields: [
      { key: "enabled", type: "boolean", label: "Hiển thị khối" },
      { key: "eyebrow", type: "text", label: "Dòng nhỏ", max: 80 },
      { key: "title", type: "textarea", label: "Tiêu đề", max: 180 },
      { key: "body1", type: "textarea", label: "Đoạn mô tả 1", max: 500 },
      { key: "body2", type: "textarea", label: "Đoạn mô tả 2", max: 500 },
      {
        key: "concepts",
        type: "list",
        label: "Ba ý niệm",
        itemLabel: "Ý niệm",
        itemTitleKey: "title",
        min: 3,
        max: 3,
        fields: [
          { key: "title", type: "text", label: "Tiêu đề", max: 80, required: true },
          { key: "body", type: "textarea", label: "Mô tả", max: 300 },
        ],
      },
    ],
    defaults: {
      enabled: true,
      eyebrow: "KHỞI NGUỒN TỪ VIỆT NAM",
      title: "Một câu chuyện mới\nvề Mind–Skin Care.",
      body1: "DOPAMIND được hình thành tại Việt Nam, từ mong muốn tạo ra những trải nghiệm chăm sóc da gần gũi và có chiều sâu cảm xúc.",
      body2: "Hành trình phía trước sẽ được viết bằng những sản phẩm, câu chuyện và khoảnh khắc thật.",
      concepts: [
        { title: "Từ Việt Nam", body: "Một góc nhìn bản địa cho nghi thức chăm sóc da hiện đại." },
        { title: "15 phút", body: "Một khoảng thời gian vừa đủ để bạn chậm lại mỗi ngày." },
        { title: "Mind–Skin Care", body: "Kết nối làn da, cảm xúc và trải nghiệm trong một câu chuyện." },
      ],
    },
  },
  {
    key: "story.closing",
    group: "story",
    label: "Câu chuyện — tuyên ngôn cuối trang",
    description: "Ảnh, thông điệp lớn và trích dẫn ở gần cuối trang.",
    path: "/cau-chuyen-dopamind",
    fields: [
      { key: "enabled", type: "boolean", label: "Hiển thị khối" },
      { key: "eyebrow", type: "text", label: "Dòng nhỏ", max: 100 },
      { key: "title", type: "textarea", label: "Tiêu đề", max: 200 },
      { key: "body", type: "textarea", label: "Mô tả", max: 500 },
      { key: "image", type: "image", label: "Ảnh ngang / desktop", required: true },
      { key: "mobileImage", type: "image", label: "Ảnh dọc / điện thoại", required: true },
      { key: "imageAlt", type: "text", label: "Mô tả ảnh", max: 220 },
      { key: "quote", type: "textarea", label: "Câu trích dẫn", max: 300 },
      { key: "quoteAuthor", type: "text", label: "Tác giả / thương hiệu", max: 60 },
    ],
    defaults: {
      enabled: true,
      eyebrow: "CHĂM DA, NHƯNG KHÔNG CHỈ LÀ CHĂM DA",
      title: "Một khoảng thời gian\ndành cho làn da.\nVà dành cho bạn.",
      body: "DOPAMIND muốn mỗi nghi thức chăm sóc da trở thành một khoảnh khắc bạn có thể chậm lại, chăm sóc bản thân và bước tiếp với cảm giác dễ chịu hơn.",
      image: "/images/homepage/moments/M02.png",
      mobileImage: "/images/homepage/ritual/R05.png",
      imageAlt: "Một khoảng thời gian thư thả dành cho bản thân",
      quote: "Đôi khi, điều chúng ta cần không phải là làm thêm — mà chỉ là một khoảng thời gian thật sự dành cho mình.",
      quoteAuthor: "DOPAMIND",
    },
  },
  {
    key: "story.cta",
    group: "story",
    label: "Câu chuyện — lời kêu gọi",
    description: "Tiêu đề, mô tả và hai nút ở cuối trang Câu chuyện.",
    path: "/cau-chuyen-dopamind",
    fields: [
      { key: "enabled", type: "boolean", label: "Hiển thị khối" },
      { key: "title", type: "textarea", label: "Tiêu đề", max: 180 },
      { key: "body", type: "textarea", label: "Mô tả", max: 500 },
      { key: "primaryLabel", type: "text", label: "Nút chính — chữ", max: 60 },
      { key: "primaryHref", type: "url", label: "Nút chính — đường dẫn" },
      { key: "secondaryLabel", type: "text", label: "Nút phụ — chữ", max: 60 },
      { key: "secondaryHref", type: "url", label: "Nút phụ — đường dẫn" },
    ],
    defaults: {
      enabled: true,
      title: "Câu chuyện tiếp theo\nbắt đầu từ\n15 phút của bạn.",
      body: "Khám phá DOPAMIND và tìm một trải nghiệm phù hợp với khoảng thời gian bạn muốn dành cho chính mình.",
      primaryLabel: "KHÁM PHÁ SẢN PHẨM",
      primaryHref: "/san-pham",
      secondaryLabel: "NGHI THỨC 15 PHÚT",
      secondaryHref: "/#nghi-thuc-15-phut",
    },
  },

  // ---------------------------------------------------------------- Trang sản phẩm
  {
    key: "shop.hero",
    group: "shop",
    label: "Trang sản phẩm — banner",
    description: "Ảnh banner, tiêu đề và lời giới thiệu phía trên danh mục sản phẩm.",
    path: "/san-pham",
    fields: [
      { key: "enabled", type: "boolean", label: "Hiển thị banner" },
      { key: "eyebrow", type: "text", label: "Dòng nhỏ", max: 80 },
      { key: "title", type: "text", label: "Tiêu đề", max: 80 },
      { key: "titleEm", type: "text", label: "Phần tiêu đề màu tím", max: 80 },
      { key: "body", type: "textarea", label: "Mô tả", max: 300, help: "Dùng {count} để tự điền số sản phẩm đang bán." },
      { key: "image", type: "image", label: "Ảnh banner", required: true, help: "Tỉ lệ khuyến nghị 16:9." },
      { key: "imageAlt", type: "text", label: "Mô tả ảnh", max: 200 },
    ],
    defaults: {
      enabled: true,
      eyebrow: "MIND–SKIN CARE / SẢN PHẨM",
      title: "Chọn một",
      titleEm: "khoảng nghỉ.",
      body: "{count} sản phẩm DOPAMIND — chăm sóc làn da theo từng dòng sản phẩm.",
      image: "/images/san-pham-hero.jpg",
      imageAlt: "Các dòng sản phẩm DOPAMIND Mask Story",
    },
  },

  // ---------------------------------------------------------------- Nhật ký & Bài viết
  {
    key: "journal.notes",
    group: "journal",
    label: "Trang Nhật ký",
    description: "Phần đầu trang và danh sách các ghi chép ở /nhat-ky.",
    path: "/nhat-ky",
    fields: [
      { key: "eyebrow", type: "text", label: "Dòng nhỏ phía trên", max: 60 },
      { key: "line1", type: "text", label: "Tiêu đề — dòng 1", max: 60, required: true },
      { key: "line2", type: "text", label: "Tiêu đề — dòng 2 (màu tím)", max: 60 },
      { key: "body", type: "textarea", label: "Mô tả", max: 300 },
      {
        key: "notes",
        type: "list",
        label: "Các ghi chép",
        itemLabel: "Ghi chép",
        itemTitleKey: "title",
        max: 30,
        fields: [
          { key: "tag", type: "text", label: "Nhãn", max: 30 },
          { key: "title", type: "text", label: "Tiêu đề", max: 120, required: true },
          { key: "body", type: "textarea", label: "Nội dung ngắn", max: 400 },
        ],
      },
    ],
    defaults: {
      eyebrow: "DOPAMIND Editorial",
      line1: "Nhật ký của",
      line2: "những nhịp chậm.",
      body: "Ghi chép về việc nghỉ ngơi, lắng nghe cơ thể và biến chăm sóc da thành một nghi thức có chủ ý.",
      notes: [
        {
          tag: "Nghi thức",
          title: "Một khoảng dừng giữa ngày dài",
          body: "Không phải lúc nào bạn cũng cần làm thêm. Đôi khi, điều cần thiết chỉ là cho cơ thể và tâm trí một nhịp thở.",
        },
        {
          tag: "Mind–Skin",
          title: "Chăm da như một cách quay về",
          body: "DOPAMIND nhìn khoảnh khắc chăm sóc da như một tín hiệu nhỏ: đã đến lúc đặt mọi thứ xuống và chú ý đến chính mình.",
        },
        {
          tag: "15:00",
          title: "Mười lăm phút không cần hoàn hảo",
          body: "Một nghi thức đủ ngắn để hiện diện trong ngày thường, đủ dài để bạn cảm nhận sự chuyển nhịp.",
        },
      ],
    },
  },
  {
    key: "blog.hero",
    group: "journal",
    label: "Trang Bài viết — đầu trang",
    description: "Tiêu đề, mô tả và nút ở đầu trang /bai-viet.",
    path: "/bai-viet",
    fields: [
      { key: "title", type: "text", label: "Tiêu đề", max: 80, required: true },
      { key: "titleEm", type: "text", label: "Tiêu đề — phần nghiêng (xuống dòng)", max: 80 },
      { key: "body", type: "textarea", label: "Mô tả", max: 300 },
      { key: "ctaLabel", type: "text", label: "Chữ trên nút", max: 40 },
      { key: "tags", type: "text", label: "Dòng chủ đề nhỏ", max: 120 },
    ],
    defaults: {
      title: "Những điều tốt đẹp bắt đầu",
      titleEm: "từ sự dịu dàng.",
      body: "Khám phá những câu chuyện, kiến thức và cảm hứng về làn da, tâm trí và một nhịp sống cân bằng hơn.",
      ctaLabel: "Khám phá bài viết",
      tags: "Kiến thức / Cảm hứng / Rituals / Vì một làn da hạnh phúc",
    },
  },
  {
    key: "blog.featured",
    group: "journal",
    label: "Trang Bài viết — bài nổi bật",
    description: "Khối bài viết nổi bật nằm dưới phần đầu trang /bai-viet.",
    path: "/bai-viet",
    fields: [
      { key: "eyebrow", type: "text", label: "Dòng nhỏ", max: 40 },
      { key: "title", type: "text", label: "Tiêu đề", max: 120, required: true },
      { key: "body", type: "textarea", label: "Mô tả", max: 400 },
      { key: "ctaLabel", type: "text", label: "Chữ trên nút", max: 40 },
      { key: "href", type: "url", label: "Đường dẫn bài viết", help: "Dùng # nếu chưa có trang chi tiết." },
      { key: "dateLabel", type: "text", label: "Ngày hiển thị", max: 40, help: "Ví dụ: 12 Tháng 5, 2024" },
      { key: "minutes", type: "number", label: "Số phút đọc" },
      { key: "image", type: "image", label: "Ảnh (không bắt buộc)", help: "Để trống để dùng nền màu mặc định. Tỉ lệ khuyến nghị 16:9." },
    ],
    defaults: {
      eyebrow: "Nổi bật",
      title: "Làn da cũng cần được nghỉ ngơi",
      body: "Khi bạn cho phép mình chậm lại, làn da cũng có cơ hội được phục hồi. Khám phá mối liên kết diệu kỳ giữa nghỉ ngơi, cảm xúc và sức khỏe làn da.",
      ctaLabel: "Đọc bài viết",
      href: "#",
      dateLabel: "12 Tháng 5, 2024",
      minutes: 6,
      image: "",
    },
  },
  {
    key: "blog.posts",
    group: "journal",
    label: "Trang Bài viết — danh sách bài",
    description: "Các bài viết hiện trong lưới /bai-viet. Bộ lọc chủ đề tự lấy từ cột “Chủ đề” của các bài.",
    path: "/bai-viet",
    fields: [
      {
        key: "posts",
        type: "list",
        label: "Bài viết",
        itemLabel: "Bài viết",
        itemTitleKey: "title",
        max: 60,
        fields: [
          { key: "cat", type: "text", label: "Chủ đề", max: 40, required: true, help: "Ví dụ: Skin Science, Mind Reset" },
          { key: "title", type: "text", label: "Tiêu đề", max: 140, required: true },
          { key: "desc", type: "textarea", label: "Mô tả ngắn", max: 300 },
          { key: "date", type: "date", label: "Ngày đăng", required: true },
          { key: "min", type: "number", label: "Số phút đọc" },
          { key: "href", type: "url", label: "Đường dẫn bài viết", help: "Dùng # nếu chưa có trang chi tiết." },
          { key: "image", type: "image", label: "Ảnh (không bắt buộc)", help: "Để trống để dùng nền màu mặc định. Tỉ lệ khuyến nghị 4:3." },
        ],
      },
    ],
    defaults: {
      posts: [
        { cat: "Skin Science", title: "Hàng rào bảo vệ da thực sự là gì?", desc: "Hiểu đúng về hàng rào bảo vệ da để chăm sóc da khỏe mạnh và bền vững hơn mỗi ngày.", date: "2024-05-10", min: 5, href: "#", image: "" },
        { cat: "Mask Technology", title: "Điều gì tạo nên một chiếc mask khác biệt?", desc: "Không chỉ là miếng mask, mà là sự kết hợp giữa khoa học, chất liệu và trải nghiệm cảm xúc.", date: "2024-05-08", min: 6, href: "#", image: "" },
        { cat: "Mind Reset", title: "Khi tâm trí dịu lại, làn da cũng rạng rỡ hơn", desc: "Một làn da đẹp bắt đầu từ một tâm trí bình yên. Cùng khám phá nghệ thuật sống chậm.", date: "2024-05-05", min: 4, href: "#", image: "" },
        { cat: "Skin Science", title: "Những hoạt chất vàng trong chăm sóc da hiện đại", desc: "Từ Niacinamide đến Peptide, khám phá các thành phần đang tạo nên làn da khỏe đẹp hơn.", date: "2024-04-28", min: 5, href: "#", image: "" },
        { cat: "Mind Reset", title: "5 nghi thức nhỏ giúp bạn sống chậm mỗi ngày", desc: "Những thay đổi nhỏ trong thói quen có thể tạo nên phiên bản dịu dàng và hạnh phúc hơn.", date: "2024-04-24", min: 4, href: "#", image: "" },
        { cat: "Mask Technology", title: "Tương lai của mặt nạ: Cá nhân hóa trải nghiệm", desc: "Công nghệ đang mở ra một kỷ nguyên mới cho trải nghiệm chăm sóc da tại nhà.", date: "2024-04-20", min: 5, href: "#", image: "" },
      ],
    },
  },
  {
    key: "blog.closing",
    group: "journal",
    label: "Trang Bài viết — cuối trang",
    description: "Câu trích dẫn, khối kêu gọi khám phá sản phẩm và khối đăng ký nhận bài ở cuối /bai-viet.",
    path: "/bai-viet",
    fields: [
      { key: "quote", type: "textarea", label: "Câu trích dẫn", max: 200 },
      { key: "quoteAuthor", type: "text", label: "Người/nhãn hiệu trích dẫn", max: 40 },
      { key: "ctaEyebrow", type: "text", label: "Khối kêu gọi — dòng nhỏ", max: 80 },
      { key: "ctaTitle", type: "text", label: "Khối kêu gọi — tiêu đề", max: 120 },
      { key: "ctaBody", type: "textarea", label: "Khối kêu gọi — mô tả", max: 300 },
      { key: "ctaLabel", type: "text", label: "Khối kêu gọi — chữ trên nút", max: 40 },
      { key: "ctaHref", type: "url", label: "Khối kêu gọi — đường dẫn", help: "Ví dụ: /san-pham" },
      { key: "newsTitle", type: "text", label: "Đăng ký nhận bài — tiêu đề", max: 100 },
      { key: "newsBody", type: "textarea", label: "Đăng ký nhận bài — mô tả", max: 300 },
    ],
    defaults: {
      quote: "“Một làn da đẹp là kết quả của một tâm trí bình yên.”",
      quoteAuthor: "DOPAMIND",
      ctaEyebrow: "Từ những câu chuyện đến trải nghiệm thật",
      ctaTitle: "Biến tri thức thành nghi thức chăm da.",
      ctaBody: "Khám phá bộ sưu tập mặt nạ DOPAMIND, nơi khoa học và cảm xúc gặp nhau, cho một làn da rạng rỡ và một bạn phiên bản thư thái hơn mỗi ngày.",
      ctaLabel: "Khám phá sản phẩm",
      ctaHref: "/san-pham",
      newsTitle: "Nhận cảm hứng mỗi tuần.",
      newsBody: "Đăng ký để nhận những bài viết mới nhất, bí quyết chăm da và những câu chuyện truyền cảm hứng từ DOPAMIND.",
    },
  },
];

export function getSectionDef(key: string): SectionDef | undefined {
  return SECTION_DEFS.find((d) => d.key === key);
}

export function isSectionKey(key: string): boolean {
  return SECTION_DEFS.some((d) => d.key === key);
}

export function defaultsOf(key: string): SectionContent {
  return getSectionDef(key)?.defaults ?? {};
}
